version: '3.8'

services:
  tts-app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./audio:/usr/src/app/audio
    restart: unless-stopped 